#!/usr/bin/env python

import os
import shutil
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

CACHE_DIR = 'weights'

if os.path.exists(CACHE_DIR):
    shutil.rmtree(CACHE_DIR)

os.makedirs(CACHE_DIR)

model = AutoModelForCausalLM.from_pretrained("Qwen/CodeQwen1.5-7B-AWQ", cache_dir=CACHE_DIR)
tokenizer = AutoTokenizer.from_pretrained("Qwen/CodeQwen1.5-7B-AWQ", cache_dir=CACHE_DIR)